spring.application.name=gestion-pagos-viajes

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.access.expiration=1800000
jwt.refresh.bytes=20
jwt.refresh.expiration=2592000000
