export const CABA_SCHOOLS: string[] = [
  "Colegio Nacional Buenos Aires",
  "Escuela Normal Superior Nº 1 Presidente Roca",
  "Colegio Salesiano San Francisco de Sales",
  "Instituto San Martín de Tours",
  "Colegio Marianista",
  "Colegio Palermo",
  "Colegio San Agustín",
  "Colegio Guadalupe",
  "Instituto Santa Brígida",
  "Colegio del Salvador",
  "Colegio San José",
  "Colegio Inmaculada Concepción",
  "Escuela Técnica Nº 1 Otto Krause",
  "Escuela Técnica Nº 11 Federico Lacroze",
  "Colegio Pestalozzi",
  "Colegio Integral Velázquez",
  "Instituto San Roberto",
  "Colegio Nuestra Señora de Luján",
  "Colegio Los Molinos",
  "Colegio Monseñor Duprat",
  "Escuela Nº 1 Presidente Uriburu",
  "Colegio De La Salle",
  "Instituto Ballester",
  "Colegio San León Magno",
  "Colegio Champagnat",
  "Colegio Los Ceibos",
  "Instituto Don Orione",
  "Colegio Argüello",
  "Instituto Pio X",
  "Colegio Don Bosco",
  "Colegio San Román",
  "Colegio Cardenal Newman",
  "Escuela Superior de Comercio Carlos Pellegrini",
  "Colegio Nuestra Señora de la Misericordia",
  "Instituto San Pedro Nolasco",
  "Colegio Santa Unión",
  "Colegio Santa Rosa",
  "Instituto La Salle Florida",
  "Escuela Argentina Modelo",
  "Colegio Bayard",
  "Colegio Manuel Belgrano",
  "Colegio Ward",
  "Colegio Buenos Aires English High School",
  "Colegio San Carlos",
  "Colegio Cristo Rey",
  "Instituto Santísima Trinidad",
  "Colegio Lasalle Flores",
  "Colegio Santa Brígida",
  "Colegio Misericordia",
  "Colegio Nuestra Señora del Huerto",
];
